# Site settings
title: BeKind Documentation
description: >-
  BeKind - Install a K8S cluster using KIND with automated post-deployment steps
baseurl: "/bekind"
url: "https://christianh814.github.io"

# Theme settings
theme: just-the-docs
color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Heading anchors
heading_anchors: true

# Aux links
aux_links:
  "BeKind on GitHub":
    - "https://github.com/christianh814/bekind"
aux_links_new_tab: true

# Footer content
footer_content: >-
  Copyright &copy; 2024 Christian Hernandez. Distributed under the <a href="https://github.com/christianh814/bekind/blob/main/LICENSE">Apache License 2.0</a>.

# GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/christianh814/bekind"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Collections
collections_dir: docs

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-seo-tag
